language: node_js
os: linux
dist: xenial
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: 14
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
          secure: 2vLzmrAJwdF53XDp1uLk/vTSZSpj/Dc+/TAY+naqTrEcrIJFbm2Fy/J0fLMf2Mc+iaELGsOTp8XUvuAR4hq5mWbvuisT/xtiyrrE2HVzO+obGgJPOyZBkkn83dJq/V1lPe7dcOnIj/z2f5eaesWfBJa7SCJXDmM3Hr3np1RaUHyMgSkjTY7l6rmoksVpUqAh+MC/If8xzvpv2baCz0fnB28pgIXf9TXkZ70iBKBw4aW5akQi4M/qDkz+6yBqqIzaj9N2GALNflD/uNiFB5LYlkuPm4HniUytffKHzl5fhS5nMjjVmgruYRn+u+H6XJFatnEzLihV4b5cVxVio6tJ7PVHTkI0N0priJ+POroxsMSRi7tz+hcsF2UmjUwfpMB8Qj4zT45lk0A8yWOkPnGMkn8ti9exUU5wKnXHNVdA/cZNzjPW0jvm6uJSCZBQ0Xi97tknQZh9mk9lK0j7vE/08BUE788XedOqo0BcEW/sR/pcpvsLpa8H+SaiWUg1iuEcHGXTLC6HWF2/V6BgW8iCujxkbvMrpibusl1W7V0f1PxSsf3g6eaE+3PmNwdLGKgiMLE38mdkjsTitzJmx0gwtyNeAoN+3j822PC0esQkohpdBXvZ85tU1FSUOpWfe4+qzU8xUQjH2v4IVMbmAuaRYL+GO9y1bG4IK/xM+M/rjLc=
